"""Add short description, role and impact to project

Revision ID: 45df74d218ea
Revises: 7b15b678c5db
Create Date: 2025-02-09 15:01:03.293477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '45df74d218ea'
down_revision: Union[str, None] = '7b15b678c5db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('short_description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('project', sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('project', sa.Column('impact', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('technology', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('technology', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('project', 'impact')
    op.drop_column('project', 'role')
    op.drop_column('project', 'short_description')
    # ### end Alembic commands ###
