"""Add timestamps

Revision ID: 7b15b678c5db
Revises: d7ad834c8199
Create Date: 2025-02-08 20:26:30.009934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7b15b678c5db'
down_revision: Union[str, None] = 'd7ad834c8199'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('projecttechnologylink', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('technology', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('technology', 'created_at')
    op.drop_column('projecttechnologylink', 'created_at')
    op.drop_column('project', 'created_at')
    # ### end Alembic commands ###
